### ISSUE TITLE
Break here? 

### ISSUE THREAD

**Issue by IanaKhitsko** [HelenKarpenko/euro-diffusion#4]
https://github.com/HelenKarpenko/euro-diffusion/blob/04428c7994460b89ca842e218c9986a90f353c37/EuroMap.cs#L46

Break of the cycle here?

**Comment by HelenKarpenko** [comment]
We need to iterate over **ALL** countries, and if we find a completed country, we need to set the DayOfCompletion field. Therefore, a break cannot be set here.
