### ISSUE TITLE
Don't allocate memory for currencies, that are not present in country

### ISSUE THREAD

**Issue by danylkaaa** [HelenKarpenko/euro-diffusion#8]
https://github.com/HelenKarpenko/euro-diffusion/blob/04428c7994460b89ca842e218c9986a90f353c37/City.cs#L49

You always allocated memory for all currencies at each iteration. But city will not have most of currencies during most of iterations. So, just add motif to city bank only when it is required

**Comment by HelenKarpenko** [comment]
Good point! I made the appropriate changes
